# Generated from a dynamic-dispatch trace of the build workload:
#     julia --project=. --trace-dispatch=/tmp/dispatch.jl workload.jl
# filtered to MOI/GenOpt/HiGHS signatures (minus load-time entries).
# Regenerate when the ABI or the workload changes.
Base.Experimental.entrypoint(Tuple{typeof(HiGHS.__init__)})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_new_model)})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_add_variables), Ptr{Nothing}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_variable), Ptr{Nothing}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_add_constraint), Ptr{Nothing}, Ptr{Nothing}, Int32, Float64})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_constant), Ptr{Nothing}, Float64})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_scalar_nonlinear), Ptr{Nothing}, Base.Cstring, Ptr{Ptr{Nothing}}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(Base.copy), MathOptInterface.VariableIndex})
Base.Experimental.entrypoint(Tuple{typeof(Base.Iterators.only), Tuple{MathOptInterface.ScalarNonlinearFunction}})
Base.Experimental.entrypoint(Tuple{typeof(Base.getproperty), MathOptInterface.ScalarNonlinearFunction, Symbol})
Base.Experimental.entrypoint(Tuple{Type{MathOptInterface.ScalarNonlinearFunction}, Symbol, Array{Any, 1}})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:+}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._iszero), MathOptInterface.VariableIndex})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._iszero), Float64})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._add_to_quadratic!), Base.Missing, Float64, MathOptInterface.VariableIndex})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._add_to_quadratic!), MathOptInterface.ScalarQuadraticFunction{Float64}, Float64, Float64})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:-}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(Base.:(var"==")), MathOptInterface.VariableIndex, Float64})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:*}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._isone), Float64})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._iszero), MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._isone), MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:/}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_iterator), Ptr{Nothing}, Ptr{Float64}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_contiguous_variables), Ptr{Nothing}, Int64, Int64})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_float_array), Ptr{Nothing}, Ptr{Float64}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_add_group_constraint), Ptr{Nothing}, Ptr{Nothing}, Int32})
Base.Experimental.entrypoint(Tuple{GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}, GenOpt.ContiguousArrayOfVariables{1}})
Base.Experimental.entrypoint(Tuple{typeof(Base._array_for_inner), Type{GenOpt.ContiguousArrayOfVariables{1}}, Base.HasShape{1}, Tuple{Base.OneTo{Int64}}})
Base.Experimental.entrypoint(Tuple{typeof(Base.collect_to_with_first!), Array{GenOpt.ContiguousArrayOfVariables{1}, 1}, GenOpt.ContiguousArrayOfVariables{1}, Base.Generator{Array{Any, 1}, GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}}, Int64})
Base.Experimental.entrypoint(Tuple{GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}, GenOpt.IteratorIndex})
Base.Experimental.entrypoint(Tuple{typeof(Base.collect_to_with_first!), Array{Float64, 1}, Float64, Base.Generator{Array{Any, 1}, GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}}, Int64})
Base.Experimental.entrypoint(Tuple{GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}, Float64})
Base.Experimental.entrypoint(Tuple{typeof(Base._all), typeof(GenOpt._is_numeric), Array{Float64, 1}, Base.Colon})
Base.Experimental.entrypoint(Tuple{typeof(GenOpt._eval_op), Symbol, Array{Float64, 1}})
Base.Experimental.entrypoint(Tuple{typeof(Base.setindex_widen_up_to), Array{GenOpt.ContiguousArrayOfVariables{1}, 1}, Float64, Int64})
Base.Experimental.entrypoint(Tuple{typeof(Base.collect_to!), Array{Any, 1}, Base.Generator{Array{Any, 1}, GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}}, Int64, Int64})
Base.Experimental.entrypoint(Tuple{Type{Base.Generator{I, F} where F where I}, GenOpt.var"#_expand##2#_expand##3", Array{Any, 1}})
Base.Experimental.entrypoint(Tuple{typeof(Base.collect), Base.Generator{Array{Any, 1}, GenOpt.var"#_expand##2#_expand##3"}})
Base.Experimental.entrypoint(Tuple{GenOpt.var"#_expand##2#_expand##3", Float64})
Base.Experimental.entrypoint(Tuple{typeof(Base.collect_to_with_first!), Array{Int64, 1}, Int64, Base.Generator{Array{Any, 1}, GenOpt.var"#_expand##2#_expand##3"}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(Base.getindex), GenOpt.ContiguousArrayOfVariables{1}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(Base._array_for_inner), Type{MathOptInterface.VariableIndex}, Base.HasShape{1}, Tuple{Base.OneTo{Int64}}})
Base.Experimental.entrypoint(Tuple{typeof(Base.collect_to_with_first!), Array{MathOptInterface.VariableIndex, 1}, MathOptInterface.VariableIndex, Base.Generator{Array{Any, 1}, GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}}, Int64})
Base.Experimental.entrypoint(Tuple{GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}, Array{Float64, 1}})
Base.Experimental.entrypoint(Tuple{typeof(Base.collect_to_with_first!), Array{Array{Float64, 1}, 1}, Array{Float64, 1}, Base.Generator{Array{Any, 1}, GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(Base.setindex_widen_up_to), Array{MathOptInterface.VariableIndex, 1}, Float64, Int64})
Base.Experimental.entrypoint(Tuple{typeof(Base._all), typeof(GenOpt._is_numeric), Array{Any, 1}, Base.Colon})
Base.Experimental.entrypoint(Tuple{typeof(Base._array_for_inner), Type{MathOptInterface.ScalarNonlinearFunction}, Base.HasShape{1}, Tuple{Base.OneTo{Int64}}})
Base.Experimental.entrypoint(Tuple{typeof(Base.collect_to_with_first!), Array{MathOptInterface.ScalarNonlinearFunction, 1}, MathOptInterface.ScalarNonlinearFunction, Base.Generator{Array{Any, 1}, GenOpt.var"#_expand##0#_expand##1"{Array{Float64, 1}}}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(Base.setindex_widen_up_to), Array{MathOptInterface.ScalarNonlinearFunction, 1}, Float64, Int64})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._eval_if_constant), MathOptInterface.VariableIndex})
Base.Experimental.entrypoint(Tuple{typeof(Base.:(var"==")), MathOptInterface.ScalarNonlinearFunction, Float64})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_set_objective_sense), Ptr{Nothing}, Int32})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_set_objective_function), Ptr{Nothing}, Ptr{Nothing}})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_optimize), Ptr{Nothing}})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_primal_status), Ptr{Nothing}})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_get_values), Ptr{Nothing}, Ptr{Float64}, Int64})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_objective_value), Ptr{Nothing}})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:^}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._isone), MathOptInterface.VariableIndex})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD._add_to_quadratic!), Base.Missing, Float64, MathOptInterface.VariableIndex, MathOptInterface.VariableIndex})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:sin}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:cos}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:exp}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:log}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:sqrt}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(MathOptInterface.Nonlinear.SymbolicAD.simplify!), Base.Val{:abs}, MathOptInterface.ScalarNonlinearFunction})
Base.Experimental.entrypoint(Tuple{typeof(JuMPyHiGHS.jumpy_free_model), Ptr{Nothing}})
Base.Experimental.entrypoint(Tuple{typeof(HiGHS.Highs_destroy), HiGHS.Optimizer})
